### ISSUE TITLE
problem on threaded uos_File2Buffer

### ISSUE THREAD

**Issue by peruginia** [fredvs/uos#17]
Hy,
tempoutmemory was declared as a global var and if i use multiple thread of uos_File2Buffer is not a good solution..
i have implemented, in the writeout procedure the use of the pointer Streamout[x].BufferOut
and i have add a funcion called uos_Stream2Buffer (like uos_File2Buffer but with a tstream)

i post my uos.pas with my change
i are interested i have made the change for use this library with delphi...
sorry for my bad english
Alessandro

[uos.zip](https://github.com/fredvs/uos/files/1511884/uos.zip)

**Comment by fredvs** [comment]
Hello Alessandro.

> tempoutmemory was declared as a global var and if i use multiple thread of uos_File2Buffer is not a good solution.

Indeed, it was provisional.  Thanks to make me remember that.

> i post my uos.pas with my change

Wow, many thanks.  I will study your code.
Write you later.

Fre;D

**Comment by peruginia** [comment]
yes, delphi 10.2 starter edition (it's free) is ok for testing.. but i have made the change in the code without ifdef , i can publish the working code...

**Comment by fredvs** [comment]
Hello Alessandro.

Your code was commited. (Commit 014d46b..2d4983e)
Many thanks.

I did add "numbuf" parameter to uos_Stream2Buffer().
// numbuf : number of frames to add to outmemory (default : -1 = all, otherwise number max of frames) 
It can be usefull if you do not need to decode all the file.
For example to detect the BPM.

About Delphi, yes, with pleasure you may publish your code.

Fre;D


Fre;D

**Comment by fredvs** [comment]
Hello.

Added "frompos" (from position) parameter for uos_Stream2Buffer() and uos_File2Buffer().

Fre;D

**Comment by peruginia** [comment]
i still integrate change for delphi in out code, in the next days (depending on my time) i will publish the patch
